# netlify.toml

[build]
  # Directory containing the serverless functions
  functions = "netlify/functions"
  # The command to build the React frontend
  command = "cd frontend/just-built-frontend && npm run build"
  # The directory to publish, containing the built static files
  publish = "frontend/just-built-frontend/build"

[dev]
  # When running `netlify dev`, proxy requests to the React dev server
  targetPort = 3000

# This rule proxies all calls from /api/* to your Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
