# netlify.toml

[build]
  # This tells Netlify to change to this directory before running any commands.
  # It will run 'npm install' and your build command from here.
  base = "frontend/just-built-frontend"
  
  # The build command, which will be run from within the 'base' directory.
  command = "npm run build"
  
  # The directory containing the built static files, relative to the 'base' directory.
  publish = "build"

# The serverless functions directory, relative to the repository root.
# This path remains the same even when a 'base' is specified.
functions = "netlify/functions"

# This proxies all API calls to your serverless functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
